export const startChats = [
    {
        chatId: 2,
        name: 'Anna Shtuk',
        avatar: 'https://images.unsplash.com/photo-1599842057874-37393e9342df?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8Z2lybHxlbnwwfHwwfHw%3D&w=1000&q=80',
        messages: [
            {
                mine: false,
                userId: 2,
                avatar: 'https://images.unsplash.com/photo-1599842057874-37393e9342df?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8Z2lybHxlbnwwfHwwfHw%3D&w=1000&q=80',
                name: 'Anna Shtuk',
                message: 'Hello,how are you?',
                messageDate: new Date(1993, 0, 17).toString(),
            },
            {
                mine: true,
                userId: 1,
                name: 'Taras Gasyuk',
                avatar: 'https://img.freepik.com/premium-photo/young-handsome-man-with-beard-over-isolated-keeping-the-arms-crossed-in-frontal-position_1368-132662.jpg?w=360',
                message: 'Hi,pretty good thank’s and you?',
                messageDate: new Date(1991, 0, 17).toString(),
            },
            {
                mine: false,
                userId: 2,
                avatar: 'https://images.unsplash.com/photo-1599842057874-37393e9342df?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8Z2lybHxlbnwwfHwwfHw%3D&w=1000&q=80',
                name: 'Anna Shtuk',
                message: "Im good thank's,beautiful day today?",
                messageDate: new Date(1995, 0, 17).toString(),
            },
            {
                mine: false,
                userId: 2,
                avatar: 'https://images.unsplash.com/photo-1599842057874-37393e9342df?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8Z2lybHxlbnwwfHwwfHw%3D&w=1000&q=80',
                name: 'Anna Shtuk',
                message: "Your not wrong,it's magic out there.",
                messageDate: new Date(1993, 0, 17).toString(),
            },
            {
                mine: true,
                userId: 1,
                name: 'Taras Gasyuk',
                avatar: 'https://img.freepik.com/premium-photo/young-handsome-man-with-beard-over-isolated-keeping-the-arms-crossed-in-frontal-position_1368-132662.jpg?w=360',
                message: 'Think I might head off camping this afternoon',
                messageDate: new Date(1991, 0, 17).toString(),
            },
        ],
        isUnread: false,
        isOnline: true,
        isWriting: false,
    },
    {
        chatId: 4,
        name: 'Ira Hrus',
        avatar: 'https://media.istockphoto.com/photos/mature-beautiful-woman-with-red-hair-picture-id1221755378?k=20&m=1221755378&s=612x612&w=0&h=rZkb0wrSR4-Qfl-MIDbD8_2L_V2KYWOf0P_EqUveAAA=',
        messages: [],
        isUnread: false,
        isOnline: false,
        isWriting: false,
    },
    {
        chatId: 3,
        name: 'Igor Varas',
        avatar: 'https://media.istockphoto.com/photos/smiling-indian-man-looking-at-camera-picture-id1270067126?k=20&m=1270067126&s=612x612&w=0&h=ZMo10u07vCX6EWJbVp27c7jnnXM2z-VXLd-4maGePqc=',
        messages: [
            {
                mine: true,
                userId: 1,
                name: 'Taras Gasyuk',
                avatar: 'https://img.freepik.com/premium-photo/young-handsome-man-with-beard-over-isolated-keeping-the-arms-crossed-in-frontal-position_1368-132662.jpg?w=360',
                message: 'Nice weather lately',
                messageDate: new Date(1991, 0, 17).toString(),
            },
            {
                mine: false,
                userId: 3,
                avatar: 'https://media.istockphoto.com/photos/smiling-indian-man-looking-at-camera-picture-id1270067126?k=20&m=1270067126&s=612x612&w=0&h=ZMo10u07vCX6EWJbVp27c7jnnXM2z-VXLd-4maGePqc=',
                name: 'Igor Varas',
                message: 'Sure is! But they say it might rain next week',
                messageDate: new Date(1993, 0, 17).toString(),
            },
            {
                mine: true,
                userId: 1,
                name: 'Taras Gasyuk',
                avatar: 'https://img.freepik.com/premium-photo/young-handsome-man-with-beard-over-isolated-keeping-the-arms-crossed-in-frontal-position_1368-132662.jpg?w=360',
                message:
                    'I heard that, too. Still, like my grandma used to say, it’ll be good for the flowers.',
                messageDate: new Date(1991, 0, 17).toString(),
            },
            {
                mine: false,
                userId: 3,
                avatar: 'https://media.istockphoto.com/photos/smiling-indian-man-looking-at-camera-picture-id1270067126?k=20&m=1270067126&s=612x612&w=0&h=ZMo10u07vCX6EWJbVp27c7jnnXM2z-VXLd-4maGePqc=',
                name: 'Igor Varas',
                message:
                    'Definitely. I’m thinking of entering my dahlias in the Spring Spectacular in May.',
                messageDate: new Date(1993, 0, 17).toString(),
            },
            {
                mine: true,
                userId: 1,
                name: 'Taras Gasyuk',
                avatar: 'https://img.freepik.com/premium-photo/young-handsome-man-with-beard-over-isolated-keeping-the-arms-crossed-in-frontal-position_1368-132662.jpg?w=360',
                message:
                    'That’s fantastic! I hope you win. I’ll be doing my unicycle juggling at the talent show that same weekend.',
                messageDate: new Date(1991, 0, 17).toString(),
            },
            {
                mine: false,
                userId: 3,
                avatar: 'https://media.istockphoto.com/photos/smiling-indian-man-looking-at-camera-picture-id1270067126?k=20&m=1270067126&s=612x612&w=0&h=ZMo10u07vCX6EWJbVp27c7jnnXM2z-VXLd-4maGePqc=',
                name: 'Igor Varas',
                message:
                    'Really? I’ve tried to learn juggling, but I can’t get past two grapefruit',
                messageDate: new Date(1993, 0, 17).toString(),
            },
            {
                mine: true,
                userId: 1,
                name: 'Taras Gasyuk',
                avatar: 'https://img.freepik.com/premium-photo/young-handsome-man-with-beard-over-isolated-keeping-the-arms-crossed-in-frontal-position_1368-132662.jpg?w=360',
                message:
                    'Maybe you should try oranges. Sometimes smaller things are easier to handle.',
                messageDate: new Date(1991, 0, 17).toString(),
            },
            {
                mine: false,
                userId: 3,
                avatar: 'https://media.istockphoto.com/photos/smiling-indian-man-looking-at-camera-picture-id1270067126?k=20&m=1270067126&s=612x612&w=0&h=ZMo10u07vCX6EWJbVp27c7jnnXM2z-VXLd-4maGePqc=',
                name: 'Igor Varas',
                message: 'Great idea. I’ll go get some right now. Thanks!',
                messageDate: new Date(1993, 0, 17).toString(),
            },
            {
                mine: true,
                userId: 1,
                name: 'Taras Gasyuk',
                avatar: 'https://img.freepik.com/premium-photo/young-handsome-man-with-beard-over-isolated-keeping-the-arms-crossed-in-frontal-position_1368-132662.jpg?w=360',
                message: 'You’re welcome. Have a nice day!',
                messageDate: new Date(1991, 0, 17).toString(),
            },
            {
                mine: false,
                userId: 3,
                avatar: 'https://media.istockphoto.com/photos/smiling-indian-man-looking-at-camera-picture-id1270067126?k=20&m=1270067126&s=612x612&w=0&h=ZMo10u07vCX6EWJbVp27c7jnnXM2z-VXLd-4maGePqc=',
                name: 'Igor Varas',
                message: 'You too! Bye!',
                messageDate: new Date(1993, 0, 17).toString(),
            },
        ],
        isUnread: false,
        isOnline: false,
        isWriting: false,
    },
];
